language: python
python:
  - "3.7"
addons:
  apt:
    packages:
      - rsync
before_install:
  - sudo apt-get install 
# command to install dependencies
install: "python setup.py install" 
# command to run tests
script: python -mpytest
